### ISSUE TITLE
Problems running excercise 4

### ISSUE THREAD

**Issue by jerrylvx** [jurajHasik/peps-torch#1]
I use Windows and run the package on Anaconda. This is the error I received when running the second command of exercise 4
`Traceback (most recent call last):
  File "examples/ctmrg_j1j2_c4v.py", line 192, in <module>
    main()
`
`
  File "examples/ctmrg_j1j2_c4v.py", line 51, in main
    state = read_ipeps_c4v(args.instate)
`
`
  File "\peps-torch\ipeps\ipeps_c4v.py", line 105, in read_ipeps_c4v
    global_args=global_args)
`
`
  File "\peps-torch\ipeps\ipeps.py", line 285, in read_ipeps
    state = IPEPS(sites, vertexToSite, lX=lX, lY=lY, peps_args=peps_args, global_args=global_args)
`
`
  File "\peps-torch\ipeps\ipeps.py", line 104, in __init__
    assert site.dtype==self.dtype,"dtype of site "+str(coord)+" and IPEPS does not match"
AssertionError: dtype of site (0, 0) and IPEPS does not match`

**Comment by jurajHasik** [comment]
Hi,

just add --GLOBALARGS_dtype complex128
In principle this should can be inferred from input file, but right now the dtype has to be explicitly passed
in case of computation in complex domain.
